install:
	cd sqlalchemy-psycopg2 && $(MAKE)
	cd dotenv && $(MAKE)
	cd boto3 && $(MAKE)
	cd requests && $(MAKE)

clean:
	cd sqlalchemy-psycopg2 && $(MAKE) clean
	cd dotenv && $(MAKE) clean
	cd boto3 && $(MAKE) clean
	cd requests && $(MAKE) clean
